# Generated by Django 2.0.4 on 2018-05-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0007_contact_recruiter'),
        ('phone_numbers', '0003_phonenumber_number_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeterrenceCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True)),
                ('related_contacts', models.ManyToManyField(blank=True, to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='DeterrenceMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('body', models.CharField(max_length=255)),
                ('related_campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterrence_messages', to='deterrence.DeterrenceCampaign')),
                ('related_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterrence_messages', to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Deterrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='deterrents')),
                ('body', models.CharField(max_length=255, null=True)),
                ('personalize', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='deterrencemessage',
            name='related_deterrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterrence_messages', to='deterrence.Deterrent'),
        ),
        migrations.AddField(
            model_name='deterrencemessage',
            name='related_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterrence_messages', to='phone_numbers.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='deterrencecampaign',
            name='related_deterrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='deterrence.Deterrent'),
        ),
        migrations.AddField(
            model_name='deterrencecampaign',
            name='related_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='phone_numbers.PhoneNumber'),
        ),
    ]
