# Generated by Django 2.0.4 on 2018-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deterrence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deterrencecampaign',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
