# Generated by Django 2.0.4 on 2018-05-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deterrence', '0002_auto_20180507_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='deterrent',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deterrent',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
