# Generated by Django 2.0.4 on 2018-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deterrence', '0003_auto_20180507_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='deterrencemessage',
            name='sid',
            field=models.CharField(default='MMxxxxxx', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deterrent',
            name='image',
            field=models.ImageField(upload_to='./static/deterrents'),
        ),
    ]
