# Generated by Django 2.0.4 on 2018-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deterrence', '0004_auto_20180509_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='deterrencemessage',
            name='status',
            field=models.CharField(default='delivered', max_length=255),
            preserve_default=False,
        ),
    ]
