# Generated by Django 2.0.4 on 2018-05-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deterrence', '0006_auto_20180511_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deterrencecampaign',
            name='related_phone_number',
        ),
    ]
