# Generated by Django 2.0.4 on 2018-07-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0007_contact_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_up_date', models.DateTimeField(auto_now_add=True)),
                ('officer_phone_number', models.CharField(db_index=True, max_length=12)),
                ('contact_phone_number', models.CharField(db_index=True, max_length=15)),
                ('related_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Contact')),
            ],
        ),
    ]
