# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('sid', models.CharField(max_length=255)),
                ('account_sid', models.CharField(max_length=255)),
                ('service_sid', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('e164', models.CharField(max_length=255)),
                ('formatted', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
            ],
        ),
    ]
