# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_phonenumber_related_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='number_type',
            field=models.CharField(choices=[('ADV', 'Advertisement'), ('DET', 'Deterrence'), ('DEM', 'Demo'), ('DEV', 'Development'), ('STG', 'Stage'), ('TST', 'Test'), ('OPR', 'Operator')], default='ADV', max_length=3),
            preserve_default=False,
        ),
    ]
