# Generated by Django 2.0.4 on 2018-05-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0003_phonenumber_number_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='burned',
            field=models.BooleanField(default=False),
        ),
    ]
