# Generated by Django 2.0.4 on 2018-07-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20180723_2008'),
        ('phone_numbers', '0004_phonenumber_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='related_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='bots.Bot'),
        ),
    ]
