# Generated by Django 2.0.4 on 2018-07-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0005_phonenumber_related_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='related_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='bots.Bot'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='related_sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='sims.Sim'),
        ),
    ]
