# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='John',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('whitepages_first_name', models.CharField(blank=True, max_length=255)),
                ('whitepages_middle_name', models.CharField(blank=True, max_length=255)),
                ('whitepages_last_name', models.CharField(blank=True, max_length=255)),
                ('whitepages_gender', models.CharField(blank=True, max_length=255)),
                ('whitepages_address', models.CharField(blank=True, max_length=255)),
                ('whitepages_address_two', models.CharField(blank=True, max_length=255)),
                ('whitepages_city', models.CharField(blank=True, max_length=255)),
                ('whitepages_state', models.CharField(blank=True, max_length=255)),
                ('whitepages_country', models.CharField(blank=True, max_length=255)),
                ('whitepages_zip_code', models.CharField(blank=True, max_length=255)),
                ('whitepages_address_type', models.CharField(blank=True, max_length=255)),
                ('whitepages_latitude', models.FloatField(blank=True)),
                ('whitepages_longitude', models.FloatField(blank=True)),
                ('whitepages_accuracy', models.CharField(blank=True, max_length=255)),
                ('whitepages_prepaid', models.BooleanField()),
                ('whitepages_phone_type', models.BooleanField()),
                ('whitepages_identity_type', models.CharField(blank=True, max_length=255)),
                ('whitepages_business_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('phone_number_type', models.CharField(blank=True, max_length=255)),
                ('phone_number_friendly', models.CharField(blank=True, max_length=255)),
                ('nextcaller_first_name', models.CharField(blank=True, max_length=255)),
                ('nextcaller_middle_name', models.CharField(blank=True, max_length=255)),
                ('nextcaller_last_name', models.CharField(blank=True, max_length=255)),
                ('nextcaller_gender', models.CharField(blank=True, max_length=255)),
                ('nextcaller_age', models.CharField(blank=True, max_length=255)),
                ('nextcaller_marital_status', models.BooleanField()),
                ('nextcaller_children_presence', models.BooleanField()),
                ('nextcaller_address', models.CharField(blank=True, max_length=255)),
                ('nextcaller_address_two', models.CharField(blank=True, max_length=255)),
                ('nextcaller_city', models.CharField(blank=True, max_length=255)),
                ('nextcaller_state', models.CharField(blank=True, max_length=255)),
                ('nextcaller_country', models.CharField(blank=True, max_length=255)),
                ('nextcaller_zip_code', models.CharField(blank=True, max_length=255)),
                ('nextcaller_address_type', models.CharField(blank=True, max_length=255)),
                ('nextcaller_latitude', models.FloatField(blank=True)),
                ('nextcaller_longitude', models.FloatField(blank=True)),
                ('nextcaller_accuracy', models.CharField(blank=True, max_length=255)),
                ('nextcaller_prepaid', models.BooleanField()),
                ('nextcaller_phone_type', models.BooleanField()),
                ('nextcaller_identity_type', models.CharField(blank=True, max_length=255)),
                ('nextcaller_business_name', models.CharField(blank=True, max_length=255)),
                ('nextcaller_email', models.EmailField(blank=True, max_length=254)),
                ('nextcaller_twitter', models.CharField(blank=True, max_length=255)),
                ('nextcaller_facebook', models.CharField(blank=True, max_length=255)),
                ('nextcaller_linkedin', models.CharField(blank=True, max_length=255)),
                ('ter_username', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='john_photos/')),
            ],
        ),
    ]
