# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('johns', '0002_auto_20171017_1948'), ('johns', '0003_auto_20171017_1957'), ('johns', '0004_auto_20171018_1745'), ('johns', '0005_auto_20171018_1747'), ('johns', '0006_auto_20171018_1757'), ('johns', '0007_auto_20171018_1826')]

    dependencies = [
        ('johns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='john',
            name='whitepages_identity_type',
        ),
        migrations.AddField(
            model_name='john',
            name='arrested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='john',
            name='deterred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='john',
            name='deterrents_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='john',
            name='identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='john',
            name='registed_offender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='john',
            name='whitepages_commercial',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_phone_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='john',
            name='whitepages_business_name',
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_children_presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_marital_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_phone_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_prepaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_prepaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_accuracy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_address_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_address_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_identity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='phone_number_friendly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='phone_number_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='ter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_accuracy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_address_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_address_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_phone_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_children_presence',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_marital_status',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_phone_type',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_prepaid',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='john',
            name='whitepages_prepaid',
            field=models.NullBooleanField(default=False),
        ),
    ]
