# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johns', '0002_auto_20171017_1948_squashed_0007_auto_20171018_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='john',
            name='whitepages_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='whitepages_entity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
