# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johns', '0003_auto_20171024_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='john',
            name='nextcaller_accuracy',
        ),
        migrations.RemoveField(
            model_name='john',
            name='nextcaller_address_type',
        ),
        migrations.RemoveField(
            model_name='john',
            name='nextcaller_latitude',
        ),
        migrations.RemoveField(
            model_name='john',
            name='nextcaller_longitude',
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_high_net_worth',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_home_owner_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_household_income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_length_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_market_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='john',
            name='nextcaller_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_marital_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='john',
            name='nextcaller_phone_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
