# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_phonenumber_related_sim'),
        ('johns', '0004_auto_20171024_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='john',
            name='do_not_deter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='john',
            name='related_phone_numbers',
            field=models.ManyToManyField(to='phone_numbers.PhoneNumber'),
        ),
    ]
