# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('johns', '0001_initial'),
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarfieldSmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('garfieldsmsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.GarfieldSmsModel')),
                ('from_number', models.CharField(max_length=255)),
                ('to_number', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_john', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='johns.John')),
                ('related_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='phone_numbers.PhoneNumber')),
            ],
            bases=('sms.garfieldsmsmodel',),
        ),
    ]
