# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smsmessage_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='related_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='phone_numbers.PhoneNumber'),
        ),
    ]
