# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone_numbers', '0002_phonenumber_related_sim'),
        ('johns', '0005_auto_20171026_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('sid', models.CharField(max_length=255)),
                ('from_number', models.CharField(max_length=255)),
                ('to_number', models.CharField(max_length=255)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('related_john', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='johns.John')),
                ('related_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='phone_numbers.PhoneNumber')),
            ],
        ),
    ]
