# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
