# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='related_phone_numbers',
            field=models.ManyToManyField(to='phone_numbers.PhoneNumber'),
        ),
    ]
