# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_related_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='related_phone_numbers',
            field=models.ManyToManyField(blank=True, to='phone_numbers.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whitepages_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whitepages_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
