# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 21:24
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180313_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[contacts.models.validate_possible_number]),
        ),
    ]
