# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 21:13
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180411_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nextcaller_first_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nextcaller_last_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=255, validators=[contacts.models.validate_possible_number]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_friendly',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whitepages_first_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whitepages_last_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
