# Generated by Django 2.0.4 on 2018-04-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180423_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
