# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('friendly_name', models.CharField(max_length=255)),
                ('sid', models.CharField(max_length=255)),
                ('iccid', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('rate_plan', models.CharField(max_length=255)),
                ('receives_whispers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('related_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whispers', to='contacts.Contact')),
                ('related_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whispers', to='phone_numbers.PhoneNumber')),
            ],
        ),
    ]
