# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('friendly_name', models.CharField(max_length=255)),
                ('sid', models.CharField(max_length=255)),
                ('iccid', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('rate_plan', models.CharField(max_length=255)),
            ],
        ),
    ]
