# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('johns', '0004_auto_20171024_2027'),
        ('phone_numbers', '0002_phonenumber_related_sim'),
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('related_john', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whispers', to='johns.John')),
                ('related_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whispers', to='phone_numbers.PhoneNumber')),
            ],
        ),
    ]
