# Generated by Django 2.0.4 on 2018-07-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='debug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='human_delay_max',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='bot',
            name='human_delay_min',
            field=models.IntegerField(default=30),
        ),
    ]
