# Generated by Django 2.0.4 on 2018-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20180723_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='answers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
